services:
  cosyvoice:
    image: neosun/cosyvoice:latest
    container_name: nexus-tts-cosyvoice
    platform: linux/amd64
    ports:
      - "50000:8188"
    volumes:
      - ./outputs:/data/voices
    restart: always
    deploy:
      resources:
        limits:
          memory: 12G
