services:
  cosyvoice:
    image: neosun/cosyvoice:latest
    container_name: nexus-tts-cosyvoice
    ports:
      - "50000:8188" # 將內部 8188 對接到外部 50000
    volumes:
      - ./outputs:/data/voices
    restart: always
    deploy:
      resources:
        limits:
          memory: 8G
